language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat
install:
  - ./travis-tool.sh r_binary_install knitr
  - ./travis-tool.sh r_binary_install dplyr
  - ./travis-tool.sh r_binary_install magrittr
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install xts
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
